### ISSUE TITLE
Suggestion: Keychain Information for Macs running Sierra (10.12) or higher

### ISSUE THREAD

**Issue by sweenish** [benroose/tutorials#2]
Hopefully this is an acceptable place. I didn't want to clone the entire tutorials repo and try to submit a pull for a small change.

An extra couple lines in your ~/.ssh/config file on Macs running Sierra (10.12) or higher will allow native keychain usage on Macs; no need to add keys to ssh-agent or anything like that. I haven't yet experimented with more than my default keys, but so far it's worked well with my default keys. You only have to enter the passphrase once (ever).

In the next couple weeks I'll create a second key-pair and see if it works like I want it to.

```
# Mac specific option to use keychain (auto-passphrase)
Host *
  UseKeychain yes

# Then the rest of the config file as you have it in the repo
```

**Comment by sweenish** [comment]
I had tried creating a second key pair and getting specific keys to be used for specific accounts, but it didn't work right away, and I don't see myself with the time to learn the intricacies of openssh to get it working. 

However, the global option does work on macOS to add your passphrase into the iCloud keychain so that your key is unlocked for you every time you log in.

**Comment by benroose** [comment]
Added details in SSH tutorial for using keychain including the "UseKeychain" config option for Mac OSX.

Thanks,
Ben
